### ISSUE TITLE
ansible stalls at "Add Repo to `apt-get`"  on Ubuntu 18.10 + fix

### ISSUE THREAD

**Issue by bbtdev** [FlorianKempenich/ansible-role-erlang-elixir-phoenix#1]
on Ubuntu 18.10 dpkg -i opens a GUI and ansible stalls, we need to run:
`DEBIAN_FRONTEND=noninteractive sudo dpkg -i erlang-solutions_1.0_all.deb`

in ansible:
```
    - name: "Add Repo to `apt-get`"
      environment: 
        DEBIAN_FRONTEND: noninteractive
      command: dpkg -i "{{ erlang_repo_package }}" chdir="{{ erlang_repo_temp_dir }}"
      become: yes
```
